name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Pages
        uses: actions/configure-pages@v1

      - name: Deploy SVG
        run: |
          mkdir -p public
          cp file.svg public/
          git config --global user.name "finestilo"
          git config --global user.email "finestilo.homes@gmail.com"
          git add public
          git commit -m "Deploy SVG to GitHub Pages"
          git push origin HEAD:gh-pages
